#include "Note.h"


MidiIndex getIndex(const NoteValue &n)
{
	return static_cast<MidiIndex>(n);
}



/////NOTE/////

Note::Note(double note_length)
	: length(note_length)
{ }

Note::Note(NoteValue note_value, int note_vel, double note_length)
	: value(note_value), vel(note_vel), length(note_length)
{ }



/////SONG NOTE/////
SongNote::SongNote(Note note, double offset_to_next, bool staccato_)
	: notes(1, note), offset(offset_to_next), staccato(staccato_)
{ }

SongNote::SongNote(NoteValue note_value, int note_vel, double note_length, double offset_to_next, bool staccato_)
	: notes(1, Note(note_value, note_vel, note_length)), offset(offset_to_next), staccato(staccato_)
{ }

SongNote::SongNote(std::vector<Note> notes_, double offset_to_next, bool staccato_)
	: notes(notes_), offset(offset_to_next), staccato(staccato_)
{ }



/////SONG/////
const int Song::DEFAULT_MIDDLE_VEL = 30;

Song::Song(double beats_per_minute, const std::vector<SongNote> &treble_notes, const std::vector<SongNote> &bass_notes)
	: bpm(beats_per_minute), treble(treble_notes), bass(bass_notes),
		numTreble(treble_notes.size()), numBass(bass_notes.size())
{ }

void Song::interpret(MidiData &data, double start_time, int middle_vel, double BPM) const
{
	//Get final BPM (BPM = bpm if BPM <= 0)
	BPM = BPM*(BPM > 0) + bpm*(BPM <= 0);
	
	//Prepare vector for adding notes (overwrites data)
	data.clearNotes();

	std::vector<MidiNote> new_notes;
	new_notes.reserve(numTreble + numBass);

	//Beat lengths (seconds)
	const double	Q_NOTE = 60.0/BPM,		//Length of a quarter note
					NOTE_TAIL = Q_NOTE*0.1,	//Amount of time note length is shortened 
					TAIL_MULT = 1.0,		//General multiplier for note length
											//	(so notes arent right on top of each other)
					STACCATO = 0.5;			//Multiplier for note length if the note is staccato

	const int vel_offset = middle_vel - DEFAULT_MIDDLE_VEL;
	
	double tt = start_time;
	//Add treble notes
	for(auto tn : treble)
	{
		double length_mult = (1.0 + (STACCATO - 1.0)*(tn.staccato))*Q_NOTE*TAIL_MULT;

		for(auto n : tn.notes)
		{
			new_notes.push_back(MidiNote(getIndex(n.value), n.vel + vel_offset,
											tt, tt + n.length*length_mult - NOTE_TAIL));
		}

		tt += tn.offset*Q_NOTE;
	}
	
	double bt = start_time;
	//Add bass notes
	for(auto bn : bass)
	{
		double length_mult = (1.0 + (STACCATO - 1.0)*(bn.staccato))*Q_NOTE;

		for(auto n : bn.notes)
		{
			new_notes.push_back(MidiNote(getIndex(n.value), n.vel + vel_offset,
											bt, bt + n.length*length_mult - NOTE_TAIL));
		}

		bt += bn.offset*Q_NOTE;
	}

	//for(MidiIndex i = 0; i < NUM_MIDI_NOTES; i++)
	//	std::cout << i << " --> " << getFrequency(i) << "\n";
	//std::cout << "\n\n" << getIndex(Notes::B2) << " --> " << getFrequency(getIndex(Notes::B2)) << "\n";

	data = MidiData(new_notes);//, (bt > tt ? bt : tt) - start_time);
	
	std::cout << "DATA LENGTH:   " << data.getLength() << "\n";
}



/////////////////////
/////// SONGS ///////
/////////////////////

static const int vel = Song::DEFAULT_MIDDLE_VEL;

static const double Q_NOTE = 1.0,				//Quarter note
					H_NOTE = Q_NOTE*2.0,		//Half note
					W_NOTE = H_NOTE*2.0,		//Whole note
					E_NOTE = Q_NOTE/2.0,		//Eighth note
					S_NOTE = E_NOTE/2.0,		//Sixteenth note
					TRIPLET = 2.0/3.0,			//Multiplier for note length for a triplet note
					TQ_NOTE = Q_NOTE*TRIPLET,	//Triplet quarter note
					TE_NOTE = E_NOTE*TRIPLET,	//Triplet eighth note
					TS_NOTE = S_NOTE*TRIPLET;	//Triplet sixteenth note
					

const Song legendOfZeldaTheme1 =
	Song(	130,//BPM//

			///TREBLE CLEF (TOP HALF)///
			{	//MEASURE 1//
				SongNote({	Note(Notes::C5, vel, H_NOTE),
							Note(Notes::E4, vel, H_NOTE) },
						H_NOTE),
				SongNote(Note(Notes::REST, 0, TQ_NOTE), TQ_NOTE),
				SongNote(Note(Notes::C5, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::C5, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::C5, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::C5, vel, TE_NOTE), TE_NOTE, true),
				//MEASURE 2//
				SongNote({	Note(Notes::C5, vel, TQ_NOTE),
							Note(Notes::D4, vel, TQ_NOTE) },
						TQ_NOTE, true),
				SongNote(Note(Notes::B4f, vel, TE_NOTE), TE_NOTE, true),
				SongNote({	Note(Notes::C5, vel, Q_NOTE),
							Note(Notes::D4, vel, Q_NOTE) },
						Q_NOTE),
				SongNote(Note(Notes::REST, 0, TQ_NOTE), TQ_NOTE),
				SongNote(Note(Notes::C5, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::C5, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::C5, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::C5, vel, TE_NOTE), TE_NOTE, true),
				//MEASURE 3//
				SongNote({	Note(Notes::C5, vel, TQ_NOTE),
							Note(Notes::E4f,	vel, TQ_NOTE) },
						TQ_NOTE, true),
				SongNote(Note(Notes::B4f, vel, TE_NOTE), TE_NOTE),
				SongNote({	Note(Notes::C5, vel, Q_NOTE),
							Note(Notes::E4f, vel, Q_NOTE) },
						Q_NOTE),
				SongNote(Note(Notes::REST, 0, TQ_NOTE), TQ_NOTE),
				SongNote(Note(Notes::C5, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::C5, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::C5, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::C5, vel, TE_NOTE), TE_NOTE, true),
				//MEASURE 4//
				SongNote(Note(Notes::C5, vel, E_NOTE), E_NOTE, true),
				SongNote(Note(Notes::G4, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G4, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G4, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::G4, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G4, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G4, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::G4, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G4, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G4, vel, E_NOTE), E_NOTE, true),
				SongNote(Note(Notes::G4, vel, E_NOTE), E_NOTE, true),
				//MEASURE 5//
				SongNote({	Note(Notes::C5, vel, Q_NOTE),
							Note(Notes::E4, vel, Q_NOTE) },
						Q_NOTE, true),
				SongNote({	Note(Notes::G4, vel, Q_NOTE),
							Note(Notes::E4, vel, Q_NOTE) },
						Q_NOTE),
				SongNote(Note(Notes::REST, 0, 1.5*E_NOTE), 1.5*E_NOTE),
				SongNote(Note(Notes::C5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::C5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::D5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::E5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F5, vel, S_NOTE), S_NOTE),
				//MEASURE 6//
				SongNote({	Note(Notes::G5, vel, H_NOTE),
							Note(Notes::B4f, vel, H_NOTE) },
						H_NOTE),
				SongNote(Note(Notes::REST, 0, E_NOTE), E_NOTE),
				SongNote(Note(Notes::G5, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::G5, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::A5f, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::B5f, vel, TE_NOTE), TE_NOTE),
				//MEASURE 7//
				SongNote({	Note(Notes::C6, vel, H_NOTE),
							Note(Notes::E5f, vel, H_NOTE) },
						H_NOTE),
				SongNote(Note(Notes::REST, 0, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::C6, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::C6, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::C6, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::B5f, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::A5f, vel, TE_NOTE), TE_NOTE),
				//MEASURE 8//
				SongNote({	Note(Notes::B5f, vel, 1.5*E_NOTE),
							Note(Notes::E5f, vel, 1.5*E_NOTE) },
						1.5*E_NOTE, true),
				SongNote(Note(Notes::A5f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G5, vel, H_NOTE), H_NOTE),
				SongNote(Note(Notes::G5, vel, Q_NOTE), Q_NOTE),
				//MEASURE 9//
				SongNote(Note(Notes::F5, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A5f, vel, H_NOTE), H_NOTE),
				SongNote(Note(Notes::G5, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F5, vel, E_NOTE), E_NOTE),
				//MEASURE 10//
				SongNote(Note(Notes::E5f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::E5f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G5, vel, H_NOTE), H_NOTE),
				SongNote(Note(Notes::F5, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::E5f, vel, E_NOTE), E_NOTE),
				//MEASURE 11//
				SongNote(Note(Notes::D5, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::D5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::E5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F5s, vel, H_NOTE), H_NOTE),
				SongNote({	Note(Notes::A5, vel, Q_NOTE),
							Note(Notes::C5, vel, Q_NOTE) },
						Q_NOTE),
				//MEASURE 12//
				SongNote({	Note(Notes::G5, vel, E_NOTE),
							Note(Notes::B4, vel, E_NOTE) },
						E_NOTE, true),
				SongNote(Note(Notes::G4, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G4, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G4, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::G4, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G4, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G4, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::G4, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G4, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G4, vel, E_NOTE), E_NOTE, true),
				SongNote(Note(Notes::G4, vel, E_NOTE), E_NOTE, true),
									
				SongNote(Note(Notes::REST, 0, W_NOTE), W_NOTE)	//Rest for a whole note after song
			},
				
			///BASS CLEF (BOTTOM HALF)///
			{	//MEASURE 1//
				SongNote(Note(Notes::C3, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::C3, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::C3, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::C3, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::C3, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::C3, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::C3, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::C3, vel, TE_NOTE), TE_NOTE, true),
				//MEASURE 2//
				SongNote(Note(Notes::B2f, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::B2f, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::B2f, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::B2f, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::B2f, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::B2f, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::B2f, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::B2f, vel, TE_NOTE), TE_NOTE, true),
				//MEASURE 3//
				SongNote(Note(Notes::A2f, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::A2f, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::A2f, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::A2f, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::A2f, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::A2f, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::A2f, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::A2f, vel, TE_NOTE), TE_NOTE, true),
				//MEASURE 4//
				SongNote(Note(Notes::G2, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::G2, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::G2, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::A2, vel, E_NOTE), E_NOTE, true),
				SongNote(Note(Notes::B2, vel, E_NOTE), E_NOTE, true),
				//MEASURE 5//
				SongNote(Note(Notes::C3, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::C3, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::C3, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::B2f, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::C3, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::C3, vel, Q_NOTE), Q_NOTE, true),
				//MEASURE 6//
				SongNote(Note(Notes::B2f, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::B2f, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::B2f, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::A2f, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::B2f, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::B2f, vel, Q_NOTE), Q_NOTE, true),
				//MEASURE 7//
				SongNote(Note(Notes::A2f, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::A2f, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::A2f, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::G2f, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::A2f, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::A2f, vel, Q_NOTE), Q_NOTE, true),
				//MEASURE 8//
				SongNote(Note(Notes::E3f, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::E3f, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::E3f, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::D3, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::E3f, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::E3f, vel, Q_NOTE), Q_NOTE, true),
				//MEASURE 9//
				SongNote(Note(Notes::D3f, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::D3f, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::D3f, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::C3, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::D3f, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::D3f, vel, Q_NOTE), Q_NOTE, true),
				//MEASURE 10//
				SongNote(Note(Notes::C3, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::C3, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::C3, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::B2f, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::C3, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::C3, vel, Q_NOTE), Q_NOTE, true),
				//MEASURE 11//
				SongNote(Note(Notes::D3, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::D3, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::D3, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::C3s, vel, TE_NOTE), TE_NOTE, true),
				SongNote(Note(Notes::D3, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::D3, vel, Q_NOTE), Q_NOTE, true),
				//MEASURE 12//
				SongNote(Note(Notes::G2, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::G2, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::G2, vel, Q_NOTE), Q_NOTE, true),
				SongNote(Note(Notes::A2, vel, E_NOTE), E_NOTE, true),
				SongNote(Note(Notes::B2, vel, E_NOTE), E_NOTE, true),
				
				SongNote(Note(Notes::REST, 0, W_NOTE), W_NOTE)	//Rest for a whole note after song
			} );

				
const Song legendOfZeldaTheme2 =
	Song(	88,//BPM//

			///TREBLE CLEF (TOP HALF)///
			{	//MEASURE 1//
				SongNote(Note(Notes::B4f, vel, H_NOTE + E_NOTE), H_NOTE + E_NOTE),
				SongNote(Note(Notes::F4, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F4, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B4f, vel, E_NOTE), E_NOTE),
				//MEASURE 2//
				SongNote(Note(Notes::A4f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G4f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A4f, vel, 1.5*Q_NOTE + H_NOTE), 1.5*Q_NOTE + H_NOTE),
				//MEASURE 3//
				SongNote(Note(Notes::B4f, vel, H_NOTE + E_NOTE), H_NOTE + E_NOTE),
				SongNote(Note(Notes::F4, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F4, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B4f, vel, E_NOTE), E_NOTE),
				//MEASURE 4//
				SongNote(Note(Notes::A4, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G4, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A4, vel, 1.5*Q_NOTE + H_NOTE), 1.5*Q_NOTE + H_NOTE),
				//MEASURE 5//
				SongNote(Note(Notes::REST, 0, W_NOTE), W_NOTE),
				//MEASURE 6//
				SongNote(Note(Notes::REST, 0, W_NOTE), W_NOTE),
				//MEASURE 7//
				SongNote(Note(Notes::B4f, vel, Q_NOTE), Q_NOTE),
				SongNote(Note(Notes::F4, vel, Q_NOTE + E_NOTE), Q_NOTE + E_NOTE),
				SongNote(Note(Notes::B4f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B4f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::C5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::D5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::E5f, vel, S_NOTE), S_NOTE),
				//MEASURE 8//
				SongNote(Note(Notes::F5, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B4f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B4f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::C5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::D5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::E5f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F5, vel, H_NOTE), H_NOTE),
				//MEASURE 9//
				SongNote(Note(Notes::B4f, vel, Q_NOTE), Q_NOTE),
				SongNote(Note(Notes::F4, vel, Q_NOTE + E_NOTE), Q_NOTE + E_NOTE),
				SongNote(Note(Notes::B4f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B4f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::C5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::D5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::E5f, vel, S_NOTE), S_NOTE),
				//MEASURE 10//
				SongNote(Note(Notes::F5, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B4f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B4f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::C5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::D5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::E5f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F5, vel, H_NOTE), H_NOTE),
				//MEASURE 11//
				SongNote({	Note(Notes::B4f, vel, Q_NOTE),
							Note(Notes::D4f, vel, Q_NOTE) },
						Q_NOTE),
				SongNote({	Note(Notes::F4, vel, Q_NOTE + E_NOTE),
							Note(Notes::D4f, vel, TE_NOTE) },
						TE_NOTE),
				SongNote(Note(Notes::D4f, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::C4, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::D4f, vel, 1.5*E_NOTE), E_NOTE),
				SongNote(Note(Notes::B4f, vel, E_NOTE), S_NOTE),
				SongNote(Note(Notes::D4f, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::B4f, vel, S_NOTE),
							Note(Notes::D4f, vel, S_NOTE) },
						S_NOTE),
				SongNote({	Note(Notes::C5, vel, S_NOTE),
							Note(Notes::E4f, vel, S_NOTE) },
						S_NOTE),
				SongNote({	Note(Notes::D5, vel, S_NOTE),
							Note(Notes::F4, vel, S_NOTE) },
						S_NOTE),
				SongNote({	Note(Notes::E5f, vel, S_NOTE),
							Note(Notes::G4, vel, S_NOTE) },
						S_NOTE),
				//MEASURE 12//
				SongNote({	Note(Notes::F5, vel, H_NOTE),
							Note(Notes::A4f, vel, 1.5*E_NOTE) },
						1.5*E_NOTE),
				SongNote(Note(Notes::B4f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B4f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::C5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::D5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::E5f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F5, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F5, vel, E_NOTE), E_NOTE),
				SongNote({	Note(Notes::F5, vel, TE_NOTE),
							Note(Notes::A4f, vel, TE_NOTE) },
						TE_NOTE),
				SongNote({	Note(Notes::G5f, vel, TE_NOTE),
							Note(Notes::B4f, vel, TE_NOTE) },
						TE_NOTE),
				SongNote({	Note(Notes::A5f, vel, TE_NOTE),
							Note(Notes::C5, vel, TE_NOTE) },
						TE_NOTE),
				//MEASURE 13//
				SongNote({	Note(Notes::B5f, vel, H_NOTE + E_NOTE),
							Note(Notes::G4f, vel, 1.5*E_NOTE) },
						1.5*E_NOTE),
				SongNote(Note(Notes::G4f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G4f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A4f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B4f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::C5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::D5f, vel, 1.5*E_NOTE), E_NOTE),
				SongNote(Note(Notes::B5f, vel, E_NOTE), S_NOTE),
				SongNote(Note(Notes::D5f, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::B5f, vel, TE_NOTE),
							Note(Notes::D5f, vel, TE_NOTE) },
						TE_NOTE),
				SongNote({	Note(Notes::A5f, vel, TE_NOTE),
							Note(Notes::C5, vel, TE_NOTE) },
						TE_NOTE),
				SongNote({	Note(Notes::G5f, vel, TE_NOTE),
							Note(Notes::B4f, vel, TE_NOTE) },
						TE_NOTE),
				//MEASURE 14//
				SongNote({	Note(Notes::A5f, vel, 1.5*E_NOTE),
							Note(Notes::D5f, vel, 1.5*E_NOTE) },
						1.5*E_NOTE),
				SongNote({	Note(Notes::G5f, vel, S_NOTE),
							Note(Notes::B4f, vel, S_NOTE) },
						S_NOTE),
				SongNote({	Note(Notes::F5, vel, H_NOTE),
							Note(Notes::A4f, vel, TE_NOTE) },
						TE_NOTE),
				SongNote(Note(Notes::A4f, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::F4, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::A4f, vel, 1.5*E_NOTE), 1.5*E_NOTE),
				SongNote(Note(Notes::A4f, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::F5, vel, Q_NOTE),
							Note(Notes::A4f, vel, TE_NOTE) },
						TE_NOTE),
				SongNote(Note(Notes::F4, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::A4f, vel, TE_NOTE), TE_NOTE),
				//MEASURE 15//
				SongNote({	Note(Notes::E5f, vel, E_NOTE),
							Note(Notes::G4f, vel, E_NOTE) },
						E_NOTE),
				SongNote({	Note(Notes::E5f, vel, S_NOTE),
							Note(Notes::G4f, vel, S_NOTE) },
						S_NOTE),
				SongNote({	Note(Notes::F5, vel, S_NOTE),
							Note(Notes::F4, vel, S_NOTE) },
						S_NOTE),
				SongNote({	Note(Notes::G5f, vel, H_NOTE),
							Note(Notes::G4f, vel, E_NOTE) },
						E_NOTE),
				SongNote(Note(Notes::G4f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A4f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B4f, vel, Q_NOTE), Q_NOTE),
				SongNote({	Note(Notes::F5, vel, E_NOTE),
							Note(Notes::A4f, vel, E_NOTE) },
						E_NOTE),
				SongNote({	Note(Notes::E5f, vel, E_NOTE),
							Note(Notes::G4f, vel, E_NOTE) },
						E_NOTE),
				//MEASURE 16//
				SongNote({	Note(Notes::D5f, vel, E_NOTE),
							Note(Notes::F4, vel, E_NOTE) },
						E_NOTE),
				SongNote({	Note(Notes::D5f, vel, S_NOTE),
							Note(Notes::F4, vel, S_NOTE) },
						S_NOTE),
				SongNote({	Note(Notes::E5f, vel, S_NOTE),
							Note(Notes::E4f, vel, S_NOTE) },
						S_NOTE),
				SongNote({	Note(Notes::F5, vel, H_NOTE),
							Note(Notes::F4, vel, E_NOTE) },
						E_NOTE),
				SongNote(Note(Notes::F4, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G4f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A4f, vel, Q_NOTE), Q_NOTE),
				SongNote({	Note(Notes::E5f, vel, E_NOTE),
							Note(Notes::G4f, vel, E_NOTE) },
						E_NOTE),
				SongNote({	Note(Notes::D5f, vel, E_NOTE),
							Note(Notes::F4, vel, E_NOTE) },
						E_NOTE),
				//MEASURE 17//
				SongNote({	Note(Notes::C5, vel, E_NOTE),
							Note(Notes::E4, vel, E_NOTE) },
						E_NOTE),
				SongNote(Note(Notes::C5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::D5, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::E5, vel, H_NOTE),
							Note(Notes::E4, vel, E_NOTE) },
						E_NOTE),
				SongNote(Note(Notes::E4, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F4, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G4, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::G4, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A4, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::G5, vel, Q_NOTE),
							Note(Notes::B4f, vel, E_NOTE) },
						E_NOTE),
				SongNote(Note(Notes::C5, vel, E_NOTE), E_NOTE),
				//MEASURE 18//
				SongNote({	Note(Notes::F5, vel, E_NOTE),
							Note(Notes::A4, vel, E_NOTE) },
						E_NOTE),
				SongNote({	Note(Notes::F4, vel, S_NOTE),
							Note(Notes::A3, vel, S_NOTE) },
						S_NOTE),
				SongNote({	Note(Notes::F4, vel, S_NOTE),
							Note(Notes::A3, vel, S_NOTE) },
						S_NOTE),
				SongNote({	Note(Notes::F4, vel, E_NOTE),
							Note(Notes::A3f, vel, E_NOTE) },
						E_NOTE),
				SongNote({	Note(Notes::F4, vel, S_NOTE),
							Note(Notes::A3f, vel, S_NOTE) },
						S_NOTE),
				SongNote({	Note(Notes::F4, vel, S_NOTE),
							Note(Notes::A3f, vel, S_NOTE) },
						S_NOTE),
				SongNote({	Note(Notes::F4, vel, E_NOTE),
							Note(Notes::G3, vel, E_NOTE) },
						E_NOTE),
				SongNote({	Note(Notes::F4, vel, S_NOTE),
							Note(Notes::G3, vel, S_NOTE) },
						S_NOTE),
				SongNote({	Note(Notes::F4, vel, S_NOTE),
							Note(Notes::G3, vel, S_NOTE) },
						S_NOTE),
				SongNote({	Note(Notes::F4, vel, E_NOTE),
							Note(Notes::G3f, vel, E_NOTE) },
						E_NOTE),
				SongNote({	Note(Notes::F4, vel, E_NOTE),
							Note(Notes::G3f, vel, E_NOTE) },
						E_NOTE),
				//MEASURE 19//
				SongNote({	Note(Notes::B4f, vel, Q_NOTE),
							Note(Notes::D4, vel, Q_NOTE) },
						Q_NOTE),
				SongNote({	Note(Notes::F4, vel, Q_NOTE + E_NOTE),
							Note(Notes::D4, vel, TE_NOTE) },
						TE_NOTE),
				SongNote(Note(Notes::D4, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::C4, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::D4, vel, 1.5*E_NOTE), E_NOTE),
				SongNote(Note(Notes::B4f, vel, E_NOTE), S_NOTE),
				SongNote(Note(Notes::D4, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::B4f, vel, S_NOTE),
							Note(Notes::D4, vel, S_NOTE) },
						S_NOTE),
				SongNote({	Note(Notes::C5, vel, S_NOTE),
							Note(Notes::E4f, vel, S_NOTE) },
						S_NOTE),
				SongNote({	Note(Notes::D5, vel, S_NOTE),
							Note(Notes::F4, vel, S_NOTE) },
						S_NOTE),
				SongNote({	Note(Notes::E5f, vel, S_NOTE),
							Note(Notes::G4, vel, S_NOTE) },
						S_NOTE),
				//MEASURE 20//
				SongNote({	Note(Notes::F5, vel, H_NOTE),
							Note(Notes::A4f, vel, 1.5*E_NOTE) },
						1.5*E_NOTE),
				SongNote(Note(Notes::B4f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B4f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::C5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::D5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::E5f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F5, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F5, vel, E_NOTE), E_NOTE),
				SongNote({	Note(Notes::F5, vel, TE_NOTE),
							Note(Notes::A4f, vel, TE_NOTE) },
						TE_NOTE),
				SongNote({	Note(Notes::G5f, vel, TE_NOTE),
							Note(Notes::B4f, vel, TE_NOTE) },
						TE_NOTE),
				SongNote({	Note(Notes::A5f, vel, TE_NOTE),
							Note(Notes::C5, vel, TE_NOTE) },
						TE_NOTE),
				//MEASURE 21//
				SongNote({	Note(Notes::B5f, vel, 1.5*H_NOTE),
							Note(Notes::D5f, vel, 1.5*H_NOTE) },
						1.5*H_NOTE),
				SongNote({	Note(Notes::D6f, vel, Q_NOTE),
							Note(Notes::E5, vel, Q_NOTE) },
						Q_NOTE),
				//MEASURE 22//
				SongNote({	Note(Notes::C6, vel, Q_NOTE),
							Note(Notes::E5f, vel, Q_NOTE) },
						Q_NOTE),
				SongNote({	Note(Notes::A5, vel, H_NOTE),
							Note(Notes::C5, vel, H_NOTE) },
						H_NOTE),
				SongNote({	Note(Notes::F5, vel, Q_NOTE),
							Note(Notes::A4, vel, Q_NOTE) },
						Q_NOTE),
				//MEASURE 23//
				SongNote(Note(Notes::E3, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::B3f, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::D4f, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::E4, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::B4f, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::D5f, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::E5, vel, Q_NOTE), Q_NOTE),
				SongNote(Note(Notes::B5f, vel, Q_NOTE), Q_NOTE),
				//MEASURE 24//
				SongNote({	Note(Notes::A5, vel, Q_NOTE),
							Note(Notes::F5, vel, Q_NOTE) },
						Q_NOTE),
				SongNote({	Note(Notes::F5, vel, H_NOTE),
							Note(Notes::F4, vel, TE_NOTE) },
						TE_NOTE),
				SongNote(Note(Notes::F4, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::F4, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::F4, vel, H_NOTE), Q_NOTE),
				SongNote(Note(Notes::F5, vel, Q_NOTE), Q_NOTE),
				//MEASURE 25//
				SongNote(Note(Notes::E3, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::B3f, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::D4f, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::E4, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::B4f, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::D5f, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::E5, vel, Q_NOTE), Q_NOTE),
				SongNote(Note(Notes::B5f, vel, Q_NOTE), Q_NOTE),
				//MEASURE 26//
				SongNote({	Note(Notes::A5, vel, Q_NOTE),
							Note(Notes::F5, vel, Q_NOTE) },
						Q_NOTE),
				SongNote({	Note(Notes::F5, vel, H_NOTE),
							Note(Notes::F4, vel, TE_NOTE) },
						TE_NOTE),
				SongNote(Note(Notes::F4, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::F4, vel, TE_NOTE), TE_NOTE),
				SongNote(Note(Notes::F4, vel, H_NOTE), Q_NOTE),
				SongNote(Note(Notes::D5, vel, Q_NOTE), Q_NOTE),
				//MEASURE 27//
				SongNote({	Note(Notes::E5f, vel, 1.5*H_NOTE),
							Note(Notes::G4f, vel, 1.5*H_NOTE) },
						1.5*H_NOTE),
				SongNote({	Note(Notes::G5f, vel, Q_NOTE),
							Note(Notes::B4, vel, Q_NOTE) },
						Q_NOTE),
				//MEASURE 28//
				SongNote({	Note(Notes::F5, vel, Q_NOTE),
							Note(Notes::B4f, vel, Q_NOTE) },
						Q_NOTE),
				SongNote({	Note(Notes::D5f, vel, H_NOTE),
							Note(Notes::F4, vel, H_NOTE) },
						H_NOTE),
				SongNote({	Note(Notes::B4f, vel, Q_NOTE),
							Note(Notes::D4f, vel, Q_NOTE) },
						Q_NOTE),
				//MEASURE 29//
				SongNote({	Note(Notes::C5, vel, E_NOTE),
							Note(Notes::E4, vel, Q_NOTE) },
						E_NOTE),
				SongNote(Note(Notes::C5, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::D5, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::E5, vel, H_NOTE),
							Note(Notes::E4, vel, E_NOTE) },
						E_NOTE),
				SongNote(Note(Notes::E4, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F4, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G4, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::G4, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A4, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::G5, vel, Q_NOTE),
							Note(Notes::B4f, vel, E_NOTE) },
						E_NOTE),
				SongNote(Note(Notes::C5, vel, E_NOTE), E_NOTE),
				//MEASURE 30//
				SongNote({	Note(Notes::F5, vel, E_NOTE),
							Note(Notes::A4, vel, E_NOTE) },
						E_NOTE),
				SongNote({	Note(Notes::F4, vel, S_NOTE),
							Note(Notes::A3, vel, S_NOTE) },
						S_NOTE),
				SongNote({	Note(Notes::F4, vel, S_NOTE),
							Note(Notes::A3, vel, S_NOTE) },
						S_NOTE),
				SongNote({	Note(Notes::F4, vel, E_NOTE),
							Note(Notes::A3f, vel, E_NOTE) },
						E_NOTE),
				SongNote({	Note(Notes::F4, vel, S_NOTE),
							Note(Notes::A3f, vel, S_NOTE) },
						S_NOTE),
				SongNote({	Note(Notes::F4, vel, S_NOTE),
							Note(Notes::A3f, vel, S_NOTE) },
						S_NOTE),
				SongNote({	Note(Notes::F4, vel, E_NOTE),
							Note(Notes::G3, vel, E_NOTE) },
						E_NOTE),
				SongNote({	Note(Notes::F4, vel, S_NOTE),
							Note(Notes::G3, vel, S_NOTE) },
						S_NOTE),
				SongNote({	Note(Notes::F4, vel, S_NOTE),
							Note(Notes::G3, vel, S_NOTE) },
						S_NOTE),
				SongNote({	Note(Notes::F4, vel, E_NOTE),
							Note(Notes::G3f, vel, E_NOTE) },
						E_NOTE),
				SongNote({	Note(Notes::F4, vel, E_NOTE),
							Note(Notes::G3f, vel, E_NOTE) },
						E_NOTE),







				SongNote(Note(Notes::REST, 0, W_NOTE), W_NOTE)	//Rest for a whole note after song
			},
				
			///BASS CLEF (BOTTOM HALF)///
			{	//MEASURE 1//
				SongNote(Note(Notes::B2f, vel, Q_NOTE), Q_NOTE),
				SongNote(Note(Notes::F3, vel, Q_NOTE), Q_NOTE),
				SongNote(Note(Notes::B3f, vel, H_NOTE), H_NOTE),
				//MEASURE 2//
				SongNote(Note(Notes::A2f, vel, Q_NOTE), Q_NOTE),
				SongNote(Note(Notes::E3f, vel, Q_NOTE), Q_NOTE),
				SongNote(Note(Notes::A3f, vel, H_NOTE), H_NOTE),
				//MEASURE 3//
				SongNote(Note(Notes::G2f, vel, Q_NOTE), Q_NOTE),
				SongNote(Note(Notes::D3f, vel, Q_NOTE), Q_NOTE),
				SongNote(Note(Notes::G3f, vel, H_NOTE), H_NOTE),
				//MEASURE 4//
				SongNote(Note(Notes::F2, vel, Q_NOTE), Q_NOTE),
				SongNote(Note(Notes::C3, vel, Q_NOTE), Q_NOTE),
				SongNote(Note(Notes::F3, vel, H_NOTE), H_NOTE),
				//MEASURE 5//
				SongNote({	Note(Notes::F3, vel, E_NOTE),
							Note(Notes::D3f, vel, E_NOTE),
							Note(Notes::B2f, vel, E_NOTE)},
						E_NOTE),
				SongNote({	Note(Notes::F3, vel, S_NOTE),
							Note(Notes::B2f, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::F3, vel, E_NOTE),
							Note(Notes::B2f, vel, E_NOTE)},
						E_NOTE),
				SongNote({	Note(Notes::F3, vel, S_NOTE),
							Note(Notes::B2f, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::F3, vel, E_NOTE),
							Note(Notes::B2f, vel, E_NOTE)},
						E_NOTE),
				SongNote({	Note(Notes::F3, vel, S_NOTE),
							Note(Notes::B2f, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::F3, vel, S_NOTE),
							Note(Notes::B2f, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::F3, vel, S_NOTE),
							Note(Notes::B2f, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				//MEASURE 6//
				SongNote({	Note(Notes::F3, vel, E_NOTE),
							Note(Notes::D3f, vel, E_NOTE),
							Note(Notes::B2f, vel, E_NOTE)},
						E_NOTE),
				SongNote({	Note(Notes::F3, vel, S_NOTE),
							Note(Notes::B2f, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::F3, vel, E_NOTE),
							Note(Notes::B2f, vel, E_NOTE)},
						E_NOTE),
				SongNote({	Note(Notes::F3, vel, S_NOTE),
							Note(Notes::B2f, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::F3, vel, E_NOTE),
							Note(Notes::B2f, vel, E_NOTE)},
						E_NOTE),
				SongNote({	Note(Notes::F3, vel, S_NOTE),
							Note(Notes::B2f, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::F3, vel, S_NOTE),
							Note(Notes::B2f, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::F3, vel, S_NOTE),
							Note(Notes::B2f, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				//MEASURE 7//
				SongNote({	Note(Notes::F3, vel, E_NOTE),
							Note(Notes::B2f, vel, E_NOTE)},
						E_NOTE),
				SongNote({	Note(Notes::F3, vel, S_NOTE),
							Note(Notes::B2f, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::F3, vel, E_NOTE),
							Note(Notes::B2f, vel, E_NOTE)},
						E_NOTE),
				SongNote({	Note(Notes::F3, vel, S_NOTE),
							Note(Notes::B2f, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::F3, vel, E_NOTE),
							Note(Notes::B2f, vel, E_NOTE)},
						E_NOTE),
				SongNote({	Note(Notes::F3, vel, S_NOTE),
							Note(Notes::B2f, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::F3, vel, S_NOTE),
							Note(Notes::B2f, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::F3, vel, S_NOTE),
							Note(Notes::B2f, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				//MEASURE 8//
				SongNote({	Note(Notes::E3f, vel, E_NOTE),
							Note(Notes::A3f, vel, E_NOTE)},
						E_NOTE),
				SongNote(Note(Notes::A3f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A3f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A3f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::A3f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A3f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A3f, vel, E_NOTE), E_NOTE),
				SongNote({	Note(Notes::E3f, vel, S_NOTE),
							Note(Notes::A3f, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::A3f, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::E3f, vel, S_NOTE),
							Note(Notes::A3f, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::A3f, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::E3f, vel, S_NOTE),
							Note(Notes::A3f, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::A3f, vel, S_NOTE), S_NOTE),
				//MEASURE 9//
				SongNote({	Note(Notes::D3f, vel, E_NOTE),
							Note(Notes::G2f, vel, E_NOTE)},
						E_NOTE),
				SongNote({	Note(Notes::D3f, vel, S_NOTE),
							Note(Notes::G2f, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::G2f, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::D3f, vel, E_NOTE),
							Note(Notes::G2f, vel, E_NOTE)},
						E_NOTE),
				SongNote({	Note(Notes::D3f, vel, S_NOTE),
							Note(Notes::G2f, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::G2f, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::D3f, vel, E_NOTE),
							Note(Notes::G2f, vel, E_NOTE)},
						E_NOTE),
				SongNote({	Note(Notes::D3f, vel, S_NOTE),
							Note(Notes::G2f, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::G2f, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::D3f, vel, S_NOTE),
							Note(Notes::G2f, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::G2f, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::D3f, vel, S_NOTE),
							Note(Notes::G2f, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::G2f, vel, S_NOTE), S_NOTE),
				//MEASURE 10//
				SongNote({	Note(Notes::C3, vel, E_NOTE),
							Note(Notes::F2, vel, E_NOTE)},
						E_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, E_NOTE), E_NOTE),
				SongNote({	Note(Notes::C3, vel, S_NOTE),
							Note(Notes::F2, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::C3, vel, S_NOTE),
							Note(Notes::F2, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote({	Note(Notes::C3, vel, S_NOTE),
							Note(Notes::F2, vel, S_NOTE)},
						S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				//MEASURE 11//
				SongNote(Note(Notes::B2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				//MEASURE 12//
				SongNote(Note(Notes::A2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::A2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::A2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::A2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::A2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A2f, vel, S_NOTE), S_NOTE),
				//MEASURE 13//
				SongNote(Note(Notes::G2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::G2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::G2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::G2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::G2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G2f, vel, S_NOTE), S_NOTE),
				//MEASURE 14//
				SongNote(Note(Notes::D3f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::D3f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::D3f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::D3f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::D3f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::D3f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::D3f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::D3f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::D3f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::D3f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::D3f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::D3f, vel, S_NOTE), S_NOTE),
				//MEASURE 15//
				SongNote(Note(Notes::B2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2, vel, S_NOTE), S_NOTE),
				//MEASURE 16//
				SongNote(Note(Notes::B2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				//MEASURE 17//
				SongNote(Note(Notes::C3, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::C3, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::C3, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::C3, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::C3, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::C3, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::C3, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::C3, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::C3, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::C3, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::C3, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::C3, vel, S_NOTE), S_NOTE),
				//MEASURE 18//
				SongNote(Note(Notes::F3, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::G2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A2, vel, S_NOTE), S_NOTE),
				//MEASURE 19//
				SongNote(Note(Notes::B2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				//MEASURE 20//
				SongNote(Note(Notes::A2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::A2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::A2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::A2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::A2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::A2f, vel, S_NOTE), S_NOTE),
				//MEASURE 21//
				SongNote(Note(Notes::G2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::G2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::G2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::G2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::G2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::G2f, vel, S_NOTE), S_NOTE),
				//MEASURE 22//
				SongNote(Note(Notes::F2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				//MEASURE 23//
				SongNote(Note(Notes::E2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::E2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::E2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::E2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::E2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::E2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::E2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::E2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::E2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::E2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::E2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::E2, vel, S_NOTE), S_NOTE),
				//MEASURE 24//
				SongNote(Note(Notes::F2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				//MEASURE 25//
				SongNote(Note(Notes::E2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::E2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::E2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::E2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::E2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::E2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::E2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::E2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::E2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::E2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::E2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::E2, vel, S_NOTE), S_NOTE),
				//MEASURE 26//
				SongNote(Note(Notes::F2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				//MEASURE 27//
				SongNote(Note(Notes::B2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2, vel, S_NOTE), S_NOTE),
				//MEASURE 28//
				SongNote(Note(Notes::B2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::B2f, vel, S_NOTE), S_NOTE),
				//MEASURE 29//
				SongNote(Note(Notes::C3, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::C3, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::C3, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::C3, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::C3, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::C3, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::C3, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::C3, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::C3, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::C3, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::C3, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::C3, vel, S_NOTE), S_NOTE),
				//MEASURE 30//
				SongNote(Note(Notes::F3, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, E_NOTE), E_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),
				SongNote(Note(Notes::F2, vel, S_NOTE), S_NOTE),


				
				SongNote(Note(Notes::REST, 0, W_NOTE), W_NOTE)	//Rest for a whole note after song
			} );